# Site settings
title: Anwesha Saha
email: anwesha@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  PhD Student at Boston University | Database Systems Researcher | Former Software Developer at Oracle
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  aquaorifice

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


