# Site settings
title: Anwesha Saha
email: anwesha@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  PhD Student at Boston University | Database Systems Researcher
baseurl: "" 
url: "https://aquaorifice.github.io" 
github_username: aquaorifice

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


